// automatically generated by the FlatBuffers compiler, do not modify

package graphpipe;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Request extends Table {
  public static Request getRootAsRequest(ByteBuffer _bb) { return getRootAsRequest(_bb, new Request()); }
  public static Request getRootAsRequest(ByteBuffer _bb, Request obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public Request __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte reqType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public Table req(Table obj) { int o = __offset(6); return o != 0 ? __union(obj, o) : null; }

  public static int createRequest(FlatBufferBuilder builder,
      byte req_type,
      int reqOffset) {
    builder.startObject(2);
    Request.addReq(builder, reqOffset);
    Request.addReqType(builder, req_type);
    return Request.endRequest(builder);
  }

  public static void startRequest(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addReqType(FlatBufferBuilder builder, byte reqType) { builder.addByte(0, reqType, 0); }
  public static void addReq(FlatBufferBuilder builder, int reqOffset) { builder.addOffset(1, reqOffset, 0); }
  public static int endRequest(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishRequestBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedRequestBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }
}

