// automatically generated by the FlatBuffers compiler, do not modify

package graphpipe;

public final class Type {
  private Type() { }
  public static final byte Null = 0;
  public static final byte Uint8 = 1;
  public static final byte Int8 = 2;
  public static final byte Uint16 = 3;
  public static final byte Int16 = 4;
  public static final byte Uint32 = 5;
  public static final byte Int32 = 6;
  public static final byte Uint64 = 7;
  public static final byte Int64 = 8;
  public static final byte Float16 = 9;
  public static final byte Float32 = 10;
  public static final byte Float64 = 11;
  public static final byte String = 12;

  public static final String[] names = { "Null", "Uint8", "Int8", "Uint16", "Int16", "Uint32", "Int32", "Uint64", "Int64", "Float16", "Float32", "Float64", "String", };

  public static String name(int e) { return names[e]; }
}

